apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zu82ydabu-dotnet-basic
  janus-idp.io/tekton: zu82ydabu-dotnet-basic
  backstage.io/kubernetes-id: zu82ydabu-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zu82ydabu-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
